### PR TITLE
when using as_object(), make sure constructor arguments are passed

### PR DESCRIPTION
**Pull request by galves**

### CODE REVIEW

**Comment by tomlankhorst** [comment]
Tnx

**Comment by tomlankhorst** [comment]
This raises an error, how do you ensure $this->_object_params is set and a valid array?

**Comment by galves** [comment]
How are you raising the error?  Additional checking could be added but I think it is fine to just have feature parity with the Mysql driver..

function mysqli_fetch_object ($result, $class_name = '', $params = null) {}

function mysql_fetch_object ($result, $class_name = null, array $params = null ) {}

.. use array or NULL.

**Comment by tomlankhorst** [comment]
You are right. 
@yariks Can you please comment on this? What version of mysql module are you using?

**Comment by tomlankhorst** [comment]
Hi galves,

The following page does not list a default value for $params:

http://php.net/manual/en/mysqli-result.fetch-object.php

**Pull request merged**
